# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=200)),
                ('char_field_blank', models.CharField(blank=True, max_length=200)),
                ('char_field_choices', models.CharField(choices=[('foo', 'Foo'), ('bar', 'Bar')], max_length=200)),
                ('char_field_default', models.CharField(default='foo', max_length=200)),
                ('char_field_none', models.CharField(blank=True, max_length=200, null=True)),
                ('char_field_unique', models.CharField(max_length=200, unique=True)),
                ('date_field', models.DateField()),
                ('datetime_field', models.DateTimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=8)),
                ('email_field', models.EmailField(max_length=254)),
                ('email_field_blank', models.EmailField(blank=True, max_length=254)),
                ('email_field_max_length', models.EmailField(max_length=50)),
                ('float_field', models.FloatField()),
                ('integer_field', models.IntegerField()),
                ('null_boolean_field', models.NullBooleanField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('slug_field', models.SlugField(db_index=False)),
                ('small_integer_field', models.SmallIntegerField()),
                ('text_field', models.TextField()),
                ('time_field', models.TimeField()),
                ('url_field', models.URLField()),
            ],
        ),
    ]
