# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'rubocop', '~> 0.51.0'
gem 'simplecov', '~> 0.15.1'
gem 'yard', '~> 0.9.12'
gem 'rake', '>= 10.0', '< 14.0'
gem 'redcarpet', '~> 3.4.0'
gem 'rutie', '~> 0.0.3'
gem 'minitest', '~> 5.8.4'

group(:rspec) do
  gem 'rspec', '~> 3.0'
end
