# This file is part of Hypothesis, which may be found at
# https://github.com/HypothesisWorks/hypothesis/
#
# Copyright the Hypothesis Authors.
# Individual contributors are listed in AUTHORS.rst and the git log.
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at https://mozilla.org/MPL/2.0/.

"""Quality tests for ``basic_strategy | specific_strategy`` combinations.

Each predicate below is chosen so that random draws from the basic (open)
strategy satisfy it with probability well under 1%. That ensures the
initial failing example essentially always comes from the specific
(complicated) branch, so the test genuinely exercises the shrinker's
ability to widen out of the specific branch into the open one.
"""

import hypothesis.strategies as st
from hypothesis.strategies import (
    integers,
    just,
    lists,
    sampled_from,
    text,
)

from tests.common.debug import minimal


def test_widen_text_with_just_long_string():
    assert (
        minimal(
            text() | just("I am the very model of a modern major generator"),
            lambda s: "very model" in s,
        )
        == "very model"
    )


def test_widen_text_with_just_short_substring():
    assert minimal(text() | just("xyzzy-plover"), lambda s: "xyzzy" in s) == "xyzzy"


def test_widen_text_with_sampled_from():
    assert (
        minimal(
            text()
            | sampled_from(["quetzalcoatl-1", "quetzalcoatl-2", "quetzalcoatl-3"]),
            lambda s: "quetzalcoatl" in s,
        )
        == "quetzalcoatl"
    )


def test_widen_integers_with_just():
    # A narrow window around the just value - random ``integers()`` draws
    # hit it much less than 1% of the time.
    assert (
        minimal(
            integers() | just(5000),
            lambda n: 4990 <= n <= 5010,
        )
        == 4990
    )


def test_widen_integers_with_sampled_from():
    assert (
        minimal(
            integers() | sampled_from([4991, 4999, 5001, 5009]),
            lambda n: 4990 <= n <= 5010,
        )
        == 4990
    )


def test_widen_bounded_integers_with_just():
    assert (
        minimal(
            integers(0, 10_000) | just(5000),
            lambda n: 4990 <= n <= 5010,
        )
        == 4990
    )


def test_widen_binary_with_just():
    # ``b"abc"`` in random bytes is vanishingly rare (~L/256**3 per draw).
    assert (
        minimal(
            st.binary() | just(b"xyz-abcdefghijk-specific-bytes"),
            lambda b: b"abc" in b,
        )
        == b"abc"
    )


def test_widen_floats_with_just():
    # A narrow window well away from the typical shrink targets.
    assert (
        minimal(
            st.floats() | just(11.0),
            lambda x: 10.0 <= x <= 12.0,
        )
        == 10.0
    )


def test_widen_text_in_a_list():
    result = minimal(
        lists(text() | just("marker-specific-string"), min_size=1),
        lambda xs: any("marker" in x for x in xs),
    )
    assert result == ["marker"]


def test_widen_integers_in_a_list():
    result = minimal(
        lists(integers() | just(500), min_size=1),
        lambda xs: any(490 <= x <= 510 for x in xs),
    )
    assert result == [490]


def test_widen_three_way_one_of():
    # ``quux`` is a distinctive 4-letter sequence - essentially never
    # generated by random ``text()`` - so the initial failure comes from
    # one of the two ``just()`` branches.
    s = text() | just("quux-kangaroo") | just("wallaby-quux-kangaroo")
    assert minimal(s, lambda v: "quux" in v) == "quux"


def test_widen_text_with_builds():
    compound = st.builds(
        lambda a, b: a + " middle " + b,
        sampled_from(["alpha", "beta"]),
        sampled_from(["gamma", "delta"]),
    )
    assert minimal(text() | compound, lambda s: "middle" in s) == "middle"


# The tests below show that widening still reaches the minimum when the
# open strategy carries restrictions, as long as the specific branch's value
# respects those restrictions.


def test_widen_text_with_alphabet():
    # Random ``text(alphabet="abcd")`` draws hit the 8-character target
    # under 1% of the time.
    assert (
        minimal(
            text(alphabet="abcd") | just("aabbccdd"),
            lambda s: "aabbccdd" in s,
        )
        == "aabbccdd"
    )


def test_widen_text_with_min_size():
    # ``"hello"`` in random ``text(min_size=3)`` is extremely rare.
    assert (
        minimal(
            text(min_size=3) | just("helloworld"),
            lambda s: "hello" in s,
        )
        == "hello"
    )


def test_widen_text_with_max_size():
    # A 2-char distinctive sequence inside a 5-char cap - very rare.
    assert minimal(text(max_size=5) | just("xyz"), lambda s: "xy" in s) == "xy"


def test_widen_integers_with_min_value():
    assert (
        minimal(
            integers(min_value=10) | just(5000),
            lambda n: 4990 <= n <= 5010,
        )
        == 4990
    )


def test_widen_integers_with_max_value():
    assert (
        minimal(
            integers(max_value=100) | just(-5000),
            lambda n: -5010 <= n <= -4990,
        )
        == -4990
    )


def test_widen_integers_with_narrow_range():
    assert (
        minimal(
            integers(0, 1000) | just(500),
            lambda n: 490 <= n <= 510,
        )
        == 490
    )


def test_widen_floats_with_range():
    assert (
        minimal(
            st.floats(0.0, 100.0) | just(11.0),
            lambda x: 10.0 <= x <= 12.0,
        )
        == 10.0
    )


def test_widen_floats_no_nan():
    assert (
        minimal(
            st.floats(allow_nan=False) | just(11.0),
            lambda x: 10.0 <= x <= 12.0,
        )
        == 10.0
    )


def test_widen_binary_with_min_size():
    assert (
        minimal(
            st.binary(min_size=3) | just(b"helloworld"),
            lambda b: b"hello" in b,
        )
        == b"hello"
    )


def test_widen_binary_with_bounded_size():
    assert (
        minimal(
            st.binary(min_size=3, max_size=5) | just(b"abcde"),
            lambda b: b"abc" in b,
        )
        == b"abc"
    )
