name: Hypothesis CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - check-whole-repo-tests
          - lint
          - check-format
          - check-coverage
          - check-conjecture-coverage
          - check-py36
        python-version: ["3.6"]
        include:
          - task: check-py37
            python-version: "3.7"
          - task: check-py38
            python-version: "3.8"
          - task: check-py39
            python-version: "3.9-dev"
          # - task: check-py310
          #   python-version: "3.10-dev"
          #   continue-on-error: true
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests
      run: TASK=${{ matrix.task }} ./build.sh
