# This file is part of Hypothesis, which may be found at
# https://github.com/HypothesisWorks/hypothesis/
#
# Copyright the Hypothesis Authors.
# Individual contributors are listed in AUTHORS.rst and the git log.
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at https://mozilla.org/MPL/2.0/.

"""Quality tests for ``wide_strategy | specific_strategy`` combinations.

Each predicate below is chosen so that random draws from the wide (open)
strategy satisfy it with probability well under 1%, so that the initial
failing example essentially always comes from the specific branch. Note that
these are end-to-end smoke tests, and could in principle be satisfied without
widening - e.g. if constants discovery mined the needle from the test source
and generated it directly in the wide branch. The authoritative evidence that
widening itself rewrites the choice sequence is the
test_widening_* / test_full_shrink_* tests in tests/conjecture/test_shrinker.py,
which assert exact choice-sequence transitions.

``just()`` values deliberately do not widen: a just() draw makes no choices,
so any wide-branch encoding of its value would make the choice sequence
longer, which the shrinker never accepts.
"""

import datetime as dt

import hypothesis.strategies as st
from hypothesis.strategies import builds, integers, just, lists, sampled_from, text

from tests.common.debug import minimal


def test_widen_text_with_sampled_from():
    strat = text() | sampled_from(["quetzalcoatl-1", "quetzalcoatl-2"])
    val = minimal(strat, lambda s: "quetzalcoatl" in s)
    assert val == "quetzalcoatl"


def test_widen_integers_with_sampled_from():
    # A narrow window around the sampled values - random ``integers()`` draws
    # hit it much less than 1% of the time.
    strat = integers() | sampled_from([4991, 4999, 5001, 5009])
    val = minimal(strat, lambda n: 4990 <= n <= 5010)
    assert val == 4990


def test_widen_bounded_integers_with_sampled_from():
    strat = integers(0, 10_000) | sampled_from([4991, 5009])
    val = minimal(strat, lambda n: 4990 <= n <= 5010)
    assert val == 4990


def test_widen_binary_with_sampled_from():
    strat = st.binary() | sampled_from([b"xyz-abcdefghijk-one", b"xyz-abcdefghijk-two"])
    val = minimal(strat, lambda b: b"abc" in b)
    assert val == b"abc"


def test_widen_floats_with_sampled_from():
    # A narrow window well away from the typical shrink targets.
    strat = st.floats() | sampled_from([11.0, 11.5])
    val = minimal(strat, lambda x: 10.0 <= x <= 12.0)
    assert val == 10.0


def test_widen_text_in_a_list():
    strat = lists(text() | sampled_from(["marker-specific-string", "marker-other"]))
    val = minimal(strat, lambda xs: any("marker" in x for x in xs))
    assert val == ["marker"]


def test_widen_three_way_one_of():
    # ``quux`` is a distinctive sequence, essentially never generated by
    # random ``text()``, so the initial failure comes from a sampled branch.
    strat = (
        text()
        | sampled_from(["quux-kangaroo", "quux-wallaby"])
        | sampled_from(["numbat-quux", "quokka-quux"])
    )
    val = minimal(strat, lambda v: "quux" in v)
    assert val == "quux"


def test_widen_text_with_builds():
    compound = builds(
        lambda a, b: a + " middle " + b,
        sampled_from(["alpha", "beta"]),
        sampled_from(["gamma", "delta"]),
    )
    strat = text() | compound
    val = minimal(strat, lambda s: "middle" in s)
    assert val == "middle"


# The tests below show that widening still reaches the minimum when the wide
# strategy carries restrictions, as long as the specific branch's value
# respects those restrictions.


def test_widen_text_with_alphabet():
    strat = text(alphabet="abcd") | sampled_from(["ddaabbccdddd", "ddddccbbaadd"])
    val = minimal(strat, lambda s: "aabbccdd" in s or "ddccbbaa" in s)
    assert val == "aabbccdd"


def test_widen_text_with_min_size():
    strat = text(min_size=3) | sampled_from(["helloworld", "hellothere"])
    val = minimal(strat, lambda s: "hello" in s)
    assert val == "hello"


def test_widen_text_with_max_size():
    # A 2-char distinctive sequence inside a 5-char cap - very rare.
    strat = text(max_size=5) | sampled_from(["xyzzy", "xyzab"])
    val = minimal(strat, lambda s: "xy" in s)
    assert val == "xy"


def test_widen_integers_with_min_value():
    strat = integers(min_value=10) | sampled_from([4991, 5009])
    val = minimal(strat, lambda n: 4990 <= n <= 5010)
    assert val == 4990


def test_widen_integers_with_max_value():
    strat = integers(max_value=100) | sampled_from([-4991, -5009])
    val = minimal(strat, lambda n: -5010 <= n <= -4990)
    assert val == -4990


def test_widen_floats_with_range():
    strat = st.floats(0.0, 100.0) | sampled_from([11.0, 11.5])
    val = minimal(strat, lambda x: 10.0 <= x <= 12.0)
    assert val == 10.0


def test_widen_binary_with_min_size():
    strat = st.binary(min_size=3) | sampled_from([b"helloworld", b"hellothere"])
    val = minimal(strat, lambda b: b"hello" in b)
    assert val == b"hello"


def test_widen_skips_alternatives_that_cannot_hold_the_value():
    # booleans() can never hold these values, so widening settles on the
    # integers() branch instead.
    strat = st.booleans() | integers() | sampled_from([4991, 5009])
    val = minimal(strat, lambda n: 4990 <= n <= 5010)
    assert val == 4990


def test_widen_dates_with_compound_branch():
    # dates() re-encodes the value in as many choices as the compound branch
    # spends, so widening applies; it could not slide into e.g. datetimes(),
    # whose longer encoding the shrinker would reject.
    specific = builds(
        dt.date,
        sampled_from([2021, 2022]),
        sampled_from([6, 7]),
        sampled_from([15, 20]),
    )
    assert minimal(
        st.dates() | specific,
        lambda d: dt.date(2021, 6, 10) <= d <= dt.date(2021, 7, 1),
    ) == dt.date(2021, 6, 10)


def test_just_does_not_widen():
    # Accepted limitation: a just() span has no choices to re-encode.
    strat = text() | just("xyzzy-plover")
    val = minimal(strat, lambda s: "xyzzy" in s)
    assert val == "xyzzy-plover"


def test_single_element_sampled_from_does_not_widen():
    # sampled_from with one element collapses to just() at construction time,
    # and so inherits its limitation.
    strat = text() | sampled_from(["xyzzy-plover"])
    val = minimal(strat, lambda s: "xyzzy" in s)
    assert val == "xyzzy-plover"
