# This file is part of Hypothesis, which may be found at
# https://github.com/HypothesisWorks/hypothesis/
#
# Copyright the Hypothesis Authors.
# Individual contributors are listed in AUTHORS.rst and the git log.
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at https://mozilla.org/MPL/2.0/.

"""Quality tests for ``wide_strategy | specific_strategy`` combinations.

Each predicate below is chosen so that random draws from the wide (open)
strategy satisfy it with probability well under 1%, so that the initial
failing example essentially always comes from the specific branch. Note that
these are end-to-end smoke tests, and could in principle be satisfied without
widening - e.g. if constants discovery mined the needle from the test source
and generated it directly in the wide branch. The authoritative evidence that
widening itself rewrites the choice sequence is the
test_widening_* / test_full_shrink_* tests in tests/conjecture/test_shrinker.py,
which assert exact choice-sequence transitions.

``just()`` values deliberately do not widen: a just() draw makes no choices,
so any wide-branch encoding of its value would make the choice sequence
longer, which the shrinker never accepts. The last two tests pin that.
"""

import hypothesis.strategies as st
from hypothesis.strategies import builds, integers, just, lists, sampled_from, text

from tests.common.debug import minimal


def test_widen_text_with_sampled_from():
    assert (
        minimal(
            text() | sampled_from(["quetzalcoatl-1", "quetzalcoatl-2"]),
            lambda s: "quetzalcoatl" in s,
        )
        == "quetzalcoatl"
    )


def test_widen_integers_with_sampled_from():
    # A narrow window around the sampled values - random ``integers()`` draws
    # hit it much less than 1% of the time.
    assert (
        minimal(
            integers() | sampled_from([4991, 4999, 5001, 5009]),
            lambda n: 4990 <= n <= 5010,
        )
        == 4990
    )


def test_widen_bounded_integers_with_sampled_from():
    assert (
        minimal(
            integers(0, 10_000) | sampled_from([4991, 5009]),
            lambda n: 4990 <= n <= 5010,
        )
        == 4990
    )


def test_widen_binary_with_sampled_from():
    assert (
        minimal(
            st.binary()
            | sampled_from([b"xyz-abcdefghijk-one", b"xyz-abcdefghijk-two"]),
            lambda b: b"abc" in b,
        )
        == b"abc"
    )


def test_widen_floats_with_sampled_from():
    # A narrow window well away from the typical shrink targets.
    assert (
        minimal(
            st.floats() | sampled_from([11.0, 11.5]),
            lambda x: 10.0 <= x <= 12.0,
        )
        == 10.0
    )


def test_widen_text_in_a_list():
    result = minimal(
        lists(text() | sampled_from(["marker-specific-string", "marker-other"])),
        lambda xs: any("marker" in x for x in xs),
    )
    assert result == ["marker"]


def test_widen_three_way_one_of():
    # ``quux`` is a distinctive sequence, essentially never generated by
    # random ``text()``, so the initial failure comes from a sampled branch.
    s = (
        text()
        | sampled_from(["quux-kangaroo", "quux-wallaby"])
        | sampled_from(["numbat-quux", "quokka-quux"])
    )
    assert minimal(s, lambda v: "quux" in v) == "quux"


def test_widen_text_with_builds():
    compound = builds(
        lambda a, b: a + " middle " + b,
        sampled_from(["alpha", "beta"]),
        sampled_from(["gamma", "delta"]),
    )
    assert minimal(text() | compound, lambda s: "middle" in s) == "middle"


# The tests below show that widening still reaches the minimum when the wide
# strategy carries restrictions, as long as the specific branch's value
# respects those restrictions.


def test_widen_text_with_alphabet():
    assert (
        minimal(
            text(alphabet="abcd") | sampled_from(["ddaabbccdddd", "ddddccbbaadd"]),
            lambda s: "aabbccdd" in s or "ddccbbaa" in s,
        )
        == "aabbccdd"
    )


def test_widen_text_with_min_size():
    assert (
        minimal(
            text(min_size=3) | sampled_from(["helloworld", "hellothere"]),
            lambda s: "hello" in s,
        )
        == "hello"
    )


def test_widen_text_with_max_size():
    # A 2-char distinctive sequence inside a 5-char cap - very rare.
    assert (
        minimal(
            text(max_size=5) | sampled_from(["xyzzy", "xyzab"]), lambda s: "xy" in s
        )
        == "xy"
    )


def test_widen_integers_with_min_value():
    assert (
        minimal(
            integers(min_value=10) | sampled_from([4991, 5009]),
            lambda n: 4990 <= n <= 5010,
        )
        == 4990
    )


def test_widen_integers_with_max_value():
    assert (
        minimal(
            integers(max_value=100) | sampled_from([-4991, -5009]),
            lambda n: -5010 <= n <= -4990,
        )
        == -4990
    )


def test_widen_floats_with_range():
    assert (
        minimal(
            st.floats(0.0, 100.0) | sampled_from([11.0, 11.5]),
            lambda x: 10.0 <= x <= 12.0,
        )
        == 10.0
    )


def test_widen_binary_with_min_size():
    assert (
        minimal(
            st.binary(min_size=3) | sampled_from([b"helloworld", b"hellothere"]),
            lambda b: b"hello" in b,
        )
        == b"hello"
    )


def test_widen_skips_alternatives_that_cannot_hold_the_value():
    # booleans() can never hold these values, so widening settles on the
    # integers() branch instead.
    assert (
        minimal(
            st.booleans() | integers() | sampled_from([4991, 5009]),
            lambda n: 4990 <= n <= 5010,
        )
        == 4990
    )


def test_just_does_not_widen():
    # Accepted limitation: a just() span has no choices to re-encode.
    assert (
        minimal(text() | just("xyzzy-plover"), lambda s: "xyzzy" in s) == "xyzzy-plover"
    )


def test_single_element_sampled_from_does_not_widen():
    # sampled_from with one element collapses to just() at construction time,
    # and so inherits its limitation.
    assert (
        minimal(text() | sampled_from(["xyzzy-plover"]), lambda s: "xyzzy" in s)
        == "xyzzy-plover"
    )
